use eo2bin::Xmir;

#[test]
fn keeps_the_text_on_both_sides_of_an_entity_reference() {
    let text = "<object>\n  <o>a&apos;b</o>\n</object>\n";
    assert_eq!(Xmir::parse(text).unwrap().print(), text);
}

#[test]
fn rejects_an_element_holding_both_text_and_children() {
    let text = "<object><o>datum<o/></o></object>";
    assert!(Xmir::parse(text).is_err());
}

#[test]
fn rejects_a_comment_inside_the_tree() {
    let text = "<object><!-- note --><o/></object>";
    assert!(Xmir::parse(text).is_err());
}

#[test]
fn keeps_the_declaration_and_the_header_comment() {
    let text =
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!-- generated by the parser -->\n<object/>\n";
    assert_eq!(Xmir::parse(text).unwrap().print(), text);
}

#[test]
fn keeps_the_datum_of_an_object() {
    let text = "<object>\n  <o as=\"α0\">40-00-00-00-00-00-00-00</o>\n</object>\n";
    assert_eq!(Xmir::parse(text).unwrap().print(), text);
}

#[test]
fn prints_a_parsed_formation_back() {
    let text = "<object>\n  <o name=\"p1\"/>\n</object>\n";
    assert_eq!(Xmir::parse(text).unwrap().print(), text);
}
